# Generated by Django 4.1.1 on 2022-10-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standby_system', '0003_alter_waiting_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='Surgery',
            field=models.CharField(choices=[('C', '커트'), ('P', '펌'), ('M', '매직')], max_length=1, verbose_name='시술 선택'),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='designer',
            field=models.CharField(choices=[('j', '제시'), ('a', '가을'), ('s', '소리'), ('e', '은정'), ('d', '다은'), ('u', '미지정')], max_length=1, verbose_name='디자이너 선택'),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='name',
            field=models.CharField(max_length=10, verbose_name='대기자 이름'),
        ),
    ]
