# Generated by Django 4.1.1 on 2022-10-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standby_system', '0004_alter_waiting_surgery_alter_waiting_designer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='designer',
            field=models.CharField(choices=[('제시', '제시'), ('가을', '가을'), ('소리', '소리'), ('은정', '은정'), ('다은', '다은'), ('미지정', '미지정')], max_length=10, verbose_name='디자이너 선택'),
        ),
    ]
