# Generated by Django 4.1.1 on 2022-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standby_system', '0005_alter_waiting_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='Surgery',
            field=models.CharField(choices=[('커트', '커트'), ('펌', '펌'), ('매직', '매직')], max_length=10, verbose_name='시술 선택'),
        ),
    ]
